// C1 = Avancé
// Organisé par groupe verbal : pronominaux, 1er groupe, 2e groupe, 3e groupe

export const C1_PRONOMINAL = [
  "s'exprimer", "se reproduire", "se douter", "se contredire", "s'abstraire", "s'accaparer",
  "s'accorder", "s'accréditer", "s'activer", "s'adapter", "s'adjoindre", "s'adonner",
  "s'affronter", "s'agglutiner", "s'amplifier"
];

export const C1_GROUP1 = [
  "abolir", "abonder", "aboutir", "abraser", "abréger", "abreuver", "abriter", "abroger",
  "absenter", "absorber", "abstenir", "abstraire", "abuser", "accabler", "accalmie"
];

export const C1_GROUP2 = [
  "abolition", "abomination", "abominablement", "abominateur", "abominable", "abominer", "abondamment",
  "abondance", "abonder", "abornement", "abouté", "aboutée", "aboutement", "abouter", "aboutir"
];

export const C1_GROUP3 = [
  "absconse", "abscondre", "abscisse", "abscondit", "abscondu", "absconsus", "abseille", "absence",
  "absentéisme", "absentement", "absentéer", "absentément", "absentia", "absentiement", "absentz"
];

export const C1_ESSENTIAL_VERBS = [
  "s'exprimer",
  "se reproduire",
  "se douter",
  "approuver",
  "désapprouver",
  "réfuter",
  "revendiquer",
  "condamner",
  "contredire",
  "nuancer",
  "étayer",
  "formuler",
  "citer",
  "évoquer",
  "souligner",
  "insister",
  "démentir",
  "défendre",
  "contester",
  "interpréter",
  "approfondir",
  "synthétiser",
  "persuader",
  "déduire",
  "distinguer",
  "caractériser",
  "examiner",
  "constater",
  "évaluer",
  "estimer",
  "vérifier",
  "identifier",
  "mesurer",
  "observer",
  "confronter",
  "classer",
  "hiérarchiser",
  "conceptualiser",
  "généraliser",
  "démontrer",
  "justifier",
  "illustrer",
  "expliquer",
  "réglementer",
  "encadrer",
  "instaurer",
  "abolir",
  "maintenir",
  "supprimer",
  "restreindre",
  "garantir",
  "contrôler",
  "sanctionner",
  "attribuer",
  "retirer",
  "préserver",
  "protéger",
  "favoriser",
  "pénaliser",
  "imposer",
  "exiger",
  "appliquer",
  "modifier",
  "coordonner",
  "superviser",
  "déléguer",
  "recruter",
  "promouvoir",
  "affecter",
  "rentabiliser",
  "financer",
  "investir",
  "entreprendre",
  "accomplir",
  "concrétiser",
  "adapter",
  "anticiper",
  "restructurer",
  "fusionner",
  "externaliser",
  "moderniser",
  "innover",
  "gérer",
  "acquérir",
  "concevoir",
  "percevoir",
  "apercevoir",
  "décevoir",
  "recevoir",
  "contenir",
  "obtenir",
  "appartenir",
  "atteindre",
  "résoudre",
  "conclure",
  "traduire",
  "introduire",
  "reproduire",
  "séduire",
  "construire",
  "détruire",
  "réduire",
  "croître"
];
