import { categorizeVerbsByGroup } from "./verbGroups.js";

const A1_VERBS = [
  "aimer",
  "habiter",
  "parler",
  "écouter",
  "regarder",
  "travailler",
  "étudier",
  "apprendre",
  "demander",
  "donner",
  "acheter",
  "payer",
  "chercher",
  "trouver",
  "arriver",
  "rester",
  "manger",
  "boire",
  "porter",
  "jouer",
  "finir",
  "choisir",
  "réussir",
  "grandir",
  "grossir",
  "maigrir",
  "remplir",
  "être",
  "avoir",
  "aller",
  "faire",
  "pouvoir",
  "vouloir",
  "devoir",
  "savoir",
  "prendre",
  "venir",
  "dire",
  "lire",
  "écrire",
  "voir",
  "mettre",
  "partir",
  "sortir",
  "dormir",
  "connaître"
];

const { group1: group1verbs, group2: group2verbs, group3: group3verbs } = categorizeVerbsByGroup(A1_VERBS);

export { group1verbs, group2verbs, group3verbs };
