// B1 = Intermédiaire
// Organisé par groupe verbal : pronominaux, 1er groupe, 2e groupe, 3e groupe

export const B1_PRONOMINAL = [
  "se plaindre", "se souvenir", "s'inquiéter", "se décider", "s'améliorer", "se tromper",
  "s'endormir", "s'apercevoir", "se dépêcher", "se rencontrer", "s'échapper", "se succéder",
  "se manquer", "se mentir", "se promettre"
];

export const B1_GROUP1 = [
  "améliorer", "accélérer", "approcher", "compliquer", "considérer", "découvrir", "déranger",
  "développer", "engager", "enregistrer", "entraîner", "expliquer", "exprimer", "fabriquer", "fonctionner"
];

export const B1_GROUP2 = [
  "abolir", "accomplir", "acquérir", "admettre", "affirmer", "agir", "approuver", "assurer",
  "bannir", "bâtir", "chérir", "commettre", "comparaître", "définir", "demurer"
];

export const B1_GROUP3 = [
  "accueillir", "acquérir", "apparaître", "apprendre", "atteindre", "attendre", "avoir", "battre",
  "boire", "bouillir", "conclure", "concourir", "conduire", "confondre", "conquérir"
];

export const B1_ESSENTIAL_VERBS = [
  "se souvenir",
  "s'inquiéter",
  "se décider",
  "s'améliorer",
  "se tromper",
  "s'endormir",
  "s'apercevoir",
  "s'échapper",
  "se plaindre",
  "se rencontrer",
  "discuter",
  "exprimer",
  "décrire",
  "comparer",
  "convaincre",
  "conseiller",
  "prévenir",
  "promettre",
  "permettre",
  "empêcher",
  "participer",
  "refuser",
  "accepter",
  "suggérer",
  "proposer",
  "défendre",
  "justifier",
  "préciser",
  "citer",
  "résumer",
  "gérer",
  "développer",
  "améliorer",
  "compléter",
  "corriger",
  "traduire",
  "imprimer",
  "enregistrer",
  "télécharger",
  "vérifier",
  "signer",
  "remplir",
  "remplacer",
  "classer",
  "organiser",
  "planifier",
  "préparer",
  "embaucher",
  "licencier",
  "collaborer",
  "rejoindre",
  "poursuivre",
  "éviter",
  "accompagner",
  "déplacer",
  "réserver",
  "annuler",
  "durer",
  "changer",
  "continuer",
  "arrêter",
  "déménager",
  "installer",
  "rapporter",
  "emprunter",
  "prêter",
  "déposer",
  "récupérer",
  "transporter",
  "livrer",
  "espérer",
  "craindre",
  "regretter",
  "apprécier",
  "pardonner",
  "soutenir",
  "protéger",
  "partager",
  "appartenir",
  "dépendre",
  "souffrir",
  "s'inquiéter",
  "se disputer",
  "se fâcher",
  "se réconcilier",
  "se marier",
  "divorcer",
  "élever",
  "éduquer",
  "encourager",
  "construire",
  "détruire",
  "produire",
  "réduire",
  "cuire",
  "couvrir",
  "accueillir",
  "atteindre",
  "résoudre",
  "reconnaître",
  "disparaître",
  "apparaître",
  "naître",
  "mourir",
  "conclure",
  "transmettre",
  "survivre",
  "contenir",
  "obtenir"
];