// B2 = Intermédiaire supérieur
// Organisé par groupe verbal : pronominaux, 1er groupe, 2e groupe, 3e groupe

export const B2_PRONOMINAL = [
  "se concentrer", "se comporter", "s'étonner", "s'adapter", "se manifester", "se reproduire",
  "se contredire", "se dérouler", "s'développer", "se dissoudre", "s'évanouir", "se méfier",
  "s'évader", "se perdre", "se repentir"
];

export const B2_GROUP1 = [
  "accumuler", "affranchir", "affirmer", "aggraver", "agir", "amasser", "aménager", "amender",
  "amplifier", "amuser", "analyser", "anéantir", "animer", "annuler", "anticiper"
];

export const B2_GROUP2 = [
  "aboutir", "accabler", "accorder", "accroître", "accumuler", "acquérir", "acquitter", "adresser",
  "adjoindre", "adjurer", "admirer", "admettre", "administrer", "adopter", "adorer"
];

export const B2_GROUP3 = [
  "abattre", "abolir", "abonder", "aboutir", "accabler", "accaparer", "accéder", "accélérer",
  "accentuer", "accepter", "accident", "accidentel", "acclimater", "accommoder", "accompagner"
];

export const B2_ESSENTIAL_VERBS = [
  "se concentrer",
  "se comporter",
  "s'étonner",
  "s'adapter",
  "se manifester",
  "affirmer",
  "prétendre",
  "soutenir",
  "contester",
  "nier",
  "admettre",
  "reconnaître",
  "démontrer",
  "prouver",
  "évoquer",
  "souligner",
  "insister",
  "estimer",
  "juger",
  "considérer",
  "critiquer",
  "convaincre",
  "persuader",
  "justifier",
  "préciser",
  "recruter",
  "licencier",
  "négocier",
  "investir",
  "financer",
  "diriger",
  "superviser",
  "coordonner",
  "collaborer",
  "accomplir",
  "réaliser",
  "entreprendre",
  "planifier",
  "développer",
  "améliorer",
  "optimiser",
  "exiger",
  "proposer",
  "accepter",
  "refuser",
  "diffuser",
  "publier",
  "annoncer",
  "signaler",
  "informer",
  "révéler",
  "cacher",
  "dénoncer",
  "interdire",
  "autoriser",
  "protéger",
  "préserver",
  "respecter",
  "ignorer",
  "transmettre",
  "influencer",
  "sensibiliser",
  "favoriser",
  "empêcher",
  "défendre",
  "analyser",
  "observer",
  "mesurer",
  "identifier",
  "vérifier",
  "tester",
  "calculer",
  "expérimenter",
  "transformer",
  "fabriquer",
  "produire",
  "consommer",
  "économiser",
  "recycler",
  "réparer",
  "remplacer",
  "comparer",
  "distinguer",
  "expliquer",
  "interpréter",
  "acquérir",
  "atteindre",
  "conclure",
  "résoudre",
  "contenir",
  "obtenir",
  "maintenir",
  "appartenir",
  "disparaître",
  "apparaître",
  "survivre",
  "naître",
  "mourir",
  "traduire",
  "construire",
  "détruire",
  "réduire",
  "cuire",
  "croître",
  "vaincre",
  "approfondir",
  "illustrer",
  "résumer",
  "synthétiser",
  "caractériser",
  "définir",
  "nuancer",
  "examiner",
  "refléter",
  "représenter",
  "supposer",
  "argumenter",
  "formuler"
];
